// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: app/protobuf/tip.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url         string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Image       string `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *Tip) Reset() {
	*x = Tip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protobuf_tip_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tip) ProtoMessage() {}

func (x *Tip) ProtoReflect() protoreflect.Message {
	mi := &file_app_protobuf_tip_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tip.ProtoReflect.Descriptor instead.
func (*Tip) Descriptor() ([]byte, []int) {
	return file_app_protobuf_tip_proto_rawDescGZIP(), []int{0}
}

func (x *Tip) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tip) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Tip) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Tip) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tip) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type CreateTipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tip *Tip `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
}

func (x *CreateTipRequest) Reset() {
	*x = CreateTipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protobuf_tip_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTipRequest) ProtoMessage() {}

func (x *CreateTipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protobuf_tip_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTipRequest.ProtoReflect.Descriptor instead.
func (*CreateTipRequest) Descriptor() ([]byte, []int) {
	return file_app_protobuf_tip_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTipRequest) GetTip() *Tip {
	if x != nil {
		return x.Tip
	}
	return nil
}

type CreateTipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tip *Tip `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
}

func (x *CreateTipResponse) Reset() {
	*x = CreateTipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protobuf_tip_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTipResponse) ProtoMessage() {}

func (x *CreateTipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_protobuf_tip_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTipResponse.ProtoReflect.Descriptor instead.
func (*CreateTipResponse) Descriptor() ([]byte, []int) {
	return file_app_protobuf_tip_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTipResponse) GetTip() *Tip {
	if x != nil {
		return x.Tip
	}
	return nil
}

type DeleteTipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TipId string `protobuf:"bytes,1,opt,name=tip_id,json=tipId,proto3" json:"tip_id,omitempty"`
}

func (x *DeleteTipRequest) Reset() {
	*x = DeleteTipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protobuf_tip_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTipRequest) ProtoMessage() {}

func (x *DeleteTipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protobuf_tip_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTipRequest.ProtoReflect.Descriptor instead.
func (*DeleteTipRequest) Descriptor() ([]byte, []int) {
	return file_app_protobuf_tip_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTipRequest) GetTipId() string {
	if x != nil {
		return x.TipId
	}
	return ""
}

type DeleteTipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TipId string `protobuf:"bytes,1,opt,name=tip_id,json=tipId,proto3" json:"tip_id,omitempty"`
}

func (x *DeleteTipResponse) Reset() {
	*x = DeleteTipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protobuf_tip_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTipResponse) ProtoMessage() {}

func (x *DeleteTipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_protobuf_tip_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTipResponse.ProtoReflect.Descriptor instead.
func (*DeleteTipResponse) Descriptor() ([]byte, []int) {
	return file_app_protobuf_tip_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTipResponse) GetTipId() string {
	if x != nil {
		return x.TipId
	}
	return ""
}

type AllTipsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllTipsRequest) Reset() {
	*x = AllTipsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protobuf_tip_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllTipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTipsRequest) ProtoMessage() {}

func (x *AllTipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protobuf_tip_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTipsRequest.ProtoReflect.Descriptor instead.
func (*AllTipsRequest) Descriptor() ([]byte, []int) {
	return file_app_protobuf_tip_proto_rawDescGZIP(), []int{5}
}

type AllTipsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tip *Tip `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
}

func (x *AllTipsResponse) Reset() {
	*x = AllTipsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protobuf_tip_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllTipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTipsResponse) ProtoMessage() {}

func (x *AllTipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_protobuf_tip_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTipsResponse.ProtoReflect.Descriptor instead.
func (*AllTipsResponse) Descriptor() ([]byte, []int) {
	return file_app_protobuf_tip_proto_rawDescGZIP(), []int{6}
}

func (x *AllTipsResponse) GetTip() *Tip {
	if x != nil {
		return x.Tip
	}
	return nil
}

type SearchTipsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TipTitle string `protobuf:"bytes,1,opt,name=tip_title,json=tipTitle,proto3" json:"tip_title,omitempty"`
}

func (x *SearchTipsRequest) Reset() {
	*x = SearchTipsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protobuf_tip_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTipsRequest) ProtoMessage() {}

func (x *SearchTipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protobuf_tip_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTipsRequest.ProtoReflect.Descriptor instead.
func (*SearchTipsRequest) Descriptor() ([]byte, []int) {
	return file_app_protobuf_tip_proto_rawDescGZIP(), []int{7}
}

func (x *SearchTipsRequest) GetTipTitle() string {
	if x != nil {
		return x.TipTitle
	}
	return ""
}

type SearchTipsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tip *Tip `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
}

func (x *SearchTipsResponse) Reset() {
	*x = SearchTipsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protobuf_tip_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTipsResponse) ProtoMessage() {}

func (x *SearchTipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_protobuf_tip_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTipsResponse.ProtoReflect.Descriptor instead.
func (*SearchTipsResponse) Descriptor() ([]byte, []int) {
	return file_app_protobuf_tip_proto_rawDescGZIP(), []int{8}
}

func (x *SearchTipsResponse) GetTip() *Tip {
	if x != nil {
		return x.Tip
	}
	return nil
}

var File_app_protobuf_tip_proto protoreflect.FileDescriptor

var file_app_protobuf_tip_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x69, 0x70, 0x22, 0x75, 0x0a,
	0x03, 0x54, 0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x22, 0x2e, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x74, 0x69, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x74, 0x69, 0x70, 0x2e, 0x54, 0x69, 0x70, 0x52,
	0x03, 0x74, 0x69, 0x70, 0x22, 0x2f, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x03, 0x74, 0x69, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x74, 0x69, 0x70, 0x2e, 0x54, 0x69, 0x70,
	0x52, 0x03, 0x74, 0x69, 0x70, 0x22, 0x29, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x69, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x70, 0x49, 0x64,
	0x22, 0x2a, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x70, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e,
	0x41, 0x6c, 0x6c, 0x54, 0x69, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2d,
	0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x54, 0x69, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x03, 0x74, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x74, 0x69, 0x70, 0x2e, 0x54, 0x69, 0x70, 0x52, 0x03, 0x74, 0x69, 0x70, 0x22, 0x30, 0x0a,
	0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x69, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x70, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x70, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22,
	0x30, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x69, 0x70, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x03, 0x74, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x74, 0x69, 0x70, 0x2e, 0x54, 0x69, 0x70, 0x52, 0x03, 0x74, 0x69,
	0x70, 0x32, 0xfd, 0x01, 0x0a, 0x0a, 0x54, 0x69, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3a, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x70, 0x12, 0x15, 0x2e,
	0x74, 0x69, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x74, 0x69, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x70, 0x12, 0x15, 0x2e, 0x74, 0x69, 0x70, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x74, 0x69, 0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x41, 0x6c, 0x6c, 0x54,
	0x69, 0x70, 0x73, 0x12, 0x13, 0x2e, 0x74, 0x69, 0x70, 0x2e, 0x41, 0x6c, 0x6c, 0x54, 0x69, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x74, 0x69, 0x70, 0x2e, 0x41,
	0x6c, 0x6c, 0x54, 0x69, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x12, 0x3f, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x69, 0x70, 0x73, 0x12, 0x16,
	0x2e, 0x74, 0x69, 0x70, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x69, 0x70, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x69, 0x70, 0x2e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x54, 0x69, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_protobuf_tip_proto_rawDescOnce sync.Once
	file_app_protobuf_tip_proto_rawDescData = file_app_protobuf_tip_proto_rawDesc
)

func file_app_protobuf_tip_proto_rawDescGZIP() []byte {
	file_app_protobuf_tip_proto_rawDescOnce.Do(func() {
		file_app_protobuf_tip_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_protobuf_tip_proto_rawDescData)
	})
	return file_app_protobuf_tip_proto_rawDescData
}

var file_app_protobuf_tip_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_app_protobuf_tip_proto_goTypes = []interface{}{
	(*Tip)(nil),                // 0: tip.Tip
	(*CreateTipRequest)(nil),   // 1: tip.CreateTipRequest
	(*CreateTipResponse)(nil),  // 2: tip.CreateTipResponse
	(*DeleteTipRequest)(nil),   // 3: tip.DeleteTipRequest
	(*DeleteTipResponse)(nil),  // 4: tip.DeleteTipResponse
	(*AllTipsRequest)(nil),     // 5: tip.AllTipsRequest
	(*AllTipsResponse)(nil),    // 6: tip.AllTipsResponse
	(*SearchTipsRequest)(nil),  // 7: tip.SearchTipsRequest
	(*SearchTipsResponse)(nil), // 8: tip.SearchTipsResponse
}
var file_app_protobuf_tip_proto_depIdxs = []int32{
	0, // 0: tip.CreateTipRequest.tip:type_name -> tip.Tip
	0, // 1: tip.CreateTipResponse.tip:type_name -> tip.Tip
	0, // 2: tip.AllTipsResponse.tip:type_name -> tip.Tip
	0, // 3: tip.SearchTipsResponse.tip:type_name -> tip.Tip
	1, // 4: tip.TipService.CreateTip:input_type -> tip.CreateTipRequest
	3, // 5: tip.TipService.DeleteTip:input_type -> tip.DeleteTipRequest
	5, // 6: tip.TipService.AllTips:input_type -> tip.AllTipsRequest
	7, // 7: tip.TipService.SearchTips:input_type -> tip.SearchTipsRequest
	2, // 8: tip.TipService.CreateTip:output_type -> tip.CreateTipResponse
	4, // 9: tip.TipService.DeleteTip:output_type -> tip.DeleteTipResponse
	6, // 10: tip.TipService.AllTips:output_type -> tip.AllTipsResponse
	8, // 11: tip.TipService.SearchTips:output_type -> tip.SearchTipsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_app_protobuf_tip_proto_init() }
func file_app_protobuf_tip_proto_init() {
	if File_app_protobuf_tip_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_protobuf_tip_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protobuf_tip_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protobuf_tip_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protobuf_tip_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protobuf_tip_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protobuf_tip_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllTipsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protobuf_tip_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllTipsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protobuf_tip_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTipsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protobuf_tip_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTipsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_protobuf_tip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_protobuf_tip_proto_goTypes,
		DependencyIndexes: file_app_protobuf_tip_proto_depIdxs,
		MessageInfos:      file_app_protobuf_tip_proto_msgTypes,
	}.Build()
	File_app_protobuf_tip_proto = out.File
	file_app_protobuf_tip_proto_rawDesc = nil
	file_app_protobuf_tip_proto_goTypes = nil
	file_app_protobuf_tip_proto_depIdxs = nil
}
